### ISSUE TITLE
ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) 

### ISSUE THREAD

**Issue by livello** [TioRuben/vedirect-antbms#2]
I fixed issue #1 and got this error 

> 0;32mI (1869) BTDM_INIT: BT controller compile version [6a07b06]␛[0m
> ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x40091f9c
> file: "./main/bluetooth.c" line 82
> func: bluetoothInit
> expression: esp_bt_controller_enable(ESP_BT_MODE_CLASSIC_BT)
> 
> abort() was called at PC 0x40091f9f on core 0

[boot_log.txt](https://github.com/TioRuben/vedirect-antbms/files/8035169/boot_log.txt)
[full_log.txt](https://github.com/TioRuben/vedirect-antbms/files/8035188/full_log.txt)

**Comment by TioRuben** [comment]
@livello Just pushed the `sdkconfig` file. I remember that the configuration was a bit tricky to get both Wifi and Bluetooth working at the same time. Please pull repo and try again with new configuration.

**Comment by livello** [comment]
@TioRuben compilation and flashing successful!
