### ISSUE TITLE
How to cyclically receive data from the ANTBMS via bluetooth esp32

### ISSUE THREAD

**Issue by livello** [TioRuben/vedirect-antbms#3]
I do not have VE MPPT Solar device. Just Chinese  AntBMS. My goal is to get state from bms and to control flatpack2 psu charge current by adjust it's voltage in order of temperature. 

![image](https://user-images.githubusercontent.com/15374538/153609048-e8186af7-4016-4c62-92de-e724a39363b3.png)
![image](https://user-images.githubusercontent.com/15374538/153611077-6a154a42-2308-4fc2-862e-bcb88c0a1825.png)
![image](https://user-images.githubusercontent.com/15374538/153615311-4d9ce69f-fd28-490c-88c2-ddb226d4197b.png)
![image](https://user-images.githubusercontent.com/15374538/153615345-766effaf-ac43-4c6d-9c5e-45c5b75dcecf.png)

I changed Ant BMS mac address. Can not connect via bluetooth.
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6612
load:0x40078000,len:14780
load:0x40080400,len:3792
entry 0x40080694
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6612
load:0x40078000,len:14780
load:0x40080400,len:3792
entry 0x40080694
␛[0;32mI (26) boot: ESP-IDF v4.4-dirty 2nd stage bootloader␛[0m
␛[0;32mI (26) boot: compile time 13:54:28␛[0m
␛[0;32mI (26) boot: chip revision: 1␛[0m
␛[0;32mI (30) boot_comm: chip revision: 1, min. bootloader chip revision: 0␛[0m
␛[0;32mI (37) boot.esp32: SPI Speed      : 40MHz␛[0m
␛[0;32mI (41) boot.esp32: SPI Mode       : DIO␛[0m
␛[0;32mI (46) boot.esp32: SPI Flash Size : 4MB␛[0m
␛[0;32mI (50) boot: Enabling RNG early entropy source...␛[0m
␛[0;32mI (56) boot: Partition Table:␛[0m
␛[0;32mI (59) boot: ## Label            Usage          Type ST Offset   Length␛[0m
␛[0;32mI (67) boot:  0 nvs              WiFi data        01 02 00009000 00006000␛[0m
␛[0;32mI (74) boot:  1 phy_init         RF data          01 01 0000f000 00001000␛[0m
␛[0;32mI (82) boot:  2 factory          factory app      00 00 00010000 00200000␛[0m
␛[0;32mI (89) boot: End of partition table␛[0m
␛[0;32mI (93) boot_comm: chip revision: 1, min. application chip revision: 0␛[0m
␛[0;32mI (100) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=42d84h (273796) map␛[0m
␛[0;32mI (208) esp_image: segment 1: paddr=00052dac vaddr=3ffbdb60 size=055d8h ( 21976) load␛[0m
␛[0;32mI (217) esp_image: segment 2: paddr=0005838c vaddr=40080000 size=07c8ch ( 31884) load␛[0m
␛[0;32mI (230) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=f6ad4h (1010388) map␛[0m
␛[0;32mI (596) esp_image: segment 4: paddr=00156afc vaddr=40087c8c size=169d0h ( 92624) load␛[0m
␛[0;32mI (634) esp_image: segment 5: paddr=0016d4d4 vaddr=400c0000 size=00064h (   100) load␛[0m
␛[0;32mI (635) esp_image: segment 6: paddr=0016d540 vaddr=50000000 size=00010h (    16) load␛[0m
␛[0;32mI (655) boot: Loaded app from partition at offset 0x10000␛[0m
␛[0;32mI (655) boot: Disabling RNG early entropy source...␛[0m
␛[0;32mI (667) cpu_start: Pro cpu up.␛[0m
␛[0;32mI (667) cpu_start: Starting app cpu, entry point is 0x400813ec␛[0m
␛[0;32mI (0) cpu_start: App cpu up.␛[0m
␛[0;32mI (683) cpu_start: Pro cpu start user code␛[0m
␛[0;32mI (683) cpu_start: cpu freq: 160000000␛[0m
␛[0;32mI (683) cpu_start: Application information:␛[0m
␛[0;32mI (688) cpu_start: Project name:     main␛[0m
␛[0;32mI (692) cpu_start: App version:      80db950-dirty␛[0m
␛[0;32mI (698) cpu_start: Compile time:     Feb 11 2022 14:03:19␛[0m
␛[0;32mI (704) cpu_start: ELF file SHA256:  98fa7b4448c31ce1...␛[0m
␛[0;32mI (710) cpu_start: ESP-IDF:          v4.4-dirty␛[0m
␛[0;32mI (715) heap_init: Initializing. RAM available for dynamic allocation:␛[0m
␛[0;32mI (722) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM␛[0m
␛[0;32mI (728) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM␛[0m
␛[0;32mI (735) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM␛[0m
␛[0;32mI (741) heap_init: At 3FFCE3D8 len 00011C28 (71 KiB): DRAM␛[0m
␛[0;32mI (747) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM␛[0m
␛[0;32mI (753) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM␛[0m
␛[0;32mI (760) heap_init: At 4009E65C len 000019A4 (6 KiB): IRAM␛[0m
␛[0;32mI (767) spi_flash: detected chip: generic␛[0m
␛[0;32mI (770) spi_flash: flash io: dio␛[0m
␛[0;32mI (776) cpu_start: Starting scheduler on PRO CPU.␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
I (856) wifi:wifi driver task: 3ffd3944, prio:23, stack:6656, core=0
␛[0;32mI (856) system_api: Base MAC address is not set␛[0m
␛[0;32mI (856) system_api: read default base MAC address from EFUSE␛[0m
I (876) wifi:wifi firmware version: 7679c42
I (876) wifi:wifi certification version: v7.0
I (876) wifi:config NVS flash: enabled
I (876) wifi:config nano formating: disabled
I (876) wifi:Init data frame dynamic rx buffer num: 32
I (886) wifi:Init management frame dynamic rx buffer num: 32
I (886) wifi:Init management short buffer num: 32
I (896) wifi:Init dynamic tx buffer num: 32
I (896) wifi:Init static rx buffer size: 1600
I (896) wifi:Init static rx buffer num: 10
I (906) wifi:Init dynamic rx buffer num: 32
␛[0;32mI (906) wifi_init: rx ba win: 6␛[0m
␛[0;32mI (916) wifi_init: tcpip mbox: 32␛[0m
␛[0;32mI (916) wifi_init: udp mbox: 6␛[0m
␛[0;32mI (916) wifi_init: tcp mbox: 6␛[0m
␛[0;32mI (926) wifi_init: tcp tx win: 5744␛[0m
␛[0;32mI (926) wifi_init: tcp rx win: 5744␛[0m
␛[0;32mI (936) wifi_init: tcp mss: 1440␛[0m
␛[0;32mI (936) wifi_init: WiFi IRAM OP enabled␛[0m
␛[0;32mI (936) wifi_init: WiFi RX IRAM OP enabled␛[0m
␛[0;32mI (946) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07␛[0m
I (1046) wifi:mode : sta (80:7d:3a:81:0d:98)
I (1046) wifi:enable tsf
␛[0;32mI (1046) WIFI: wifi_init_sta finished.␛[0m
I (1056) wifi:new:<6,1>, old:<1,0>, ap:<255,255>, sta:<6,1>, prof:1
I (1066) wifi:state: init -> auth (b0)
I (1066) wifi:state: auth -> assoc (0)
I (1066) wifi:state: assoc -> run (10)
I (1176) wifi:connected with vent, aid = 1, channel 6, 40U, bssid = ec:41:18:50:ab:09
I (1176) wifi:security: WPA2-PSK, phy: bgn, rssi: -70
I (1186) wifi:pm start, type: 1

W (1196) wifi:<ba-add>idx:0 (ifx:0, ec:41:18:50:ab:09), tid:6, ssn:2, winSize:64
I (1256) wifi:AP's beacon interval = 102400 us, DTIM period = 1
␛[0;32mI (1846) esp_netif_handlers: sta ip: 10.20.0.234, mask: 255.255.255.0, gw: 10.20.0.1␛[0m
␛[0;32mI (1846) WIFI: got ip:10.20.0.234␛[0m
␛[0;32mI (1846) WIFI: connected to ap SSID:vent␛[0m
␛[0;32mI (1856) BTDM_INIT: BT controller compile version [6a07b06]␛[0m
␛[0;31mE (4506) MPPT: Block not found in 941 bytes␛[0m
␛[0;31mE (4506) MPPT: Block not found in 941 bytes␛[0m
␛[0;31mE (6516) MPPT: Block not found in 941 bytes␛[0m
␛[0;31mE (6516) MPPT: Block not found in 941 bytes␛[0m
␛[0;33mW (7606) BT_SDP: SDP - Rcvd conn cnf with error: 0x4  CID 0x40
␛[0m
␛[0;31mE (8516) MPPT: Block not found in 941 bytes␛[0m
```

**Comment by livello** [comment]
@TioRuben  trying to understand how your code works. As I understand it, the blue tooth does not display messages about the connection status to AntBMS. Moreover, I did not quite understand how the data that comes with the BMS is used.

**Comment by TioRuben** [comment]
@livello Sorry, surely I must update README for the code to be more understandable. Let me explain what I've done:
 - I've a setup with two Victron MPPTs and a AntBMS BMS to charge an 18650 battery pack in 7s50p configuration with solar power
 - I'd like to monitor everything with [EmonCMS](https://emoncms.org/)

So I've mounted an ESP32 configured with Serial1 and Serial2 connected to VE Direct ports from MPPT. Serial 0 kept for debugging. Bluetooth is configured in "classic" mode to read data from AntBMS Bluetooth classic serial port. The code is pretty much inspired from the BT Classic example of Espressif. It connects to bluetooth device, sets the PIN and connects to SPP service on the BMS. If you connect to this service, then you can send the "magic word" (0xDB, 0xDB, 0x00, 0x00, 0x00, 0x00, 0x0D, 0x0A) and the bms responds with a data packet, containing all useful information (temperature, battery voltages, SOC and so on). 

First of all, maybe the manufacturer has changed some of his parameters (usually the bluetooth address is the one in the configuration for all the bms). Then you can try with some Android app to connect to SPP service and send the magic word [this app](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal) can send messages in hex format. If it replies with some information (unintelligible for humans), then the BMS can be compatible with my code. If it doesn't, the BMS will be incompatible with my code.

If the magic word works, maybe is a connection issue. In the first tests of my code, I encountered the problem that ESP needs to be really really close to the BMS (no more than two/three meters away), if not, the connection fails. 

If anything of above works, try to run just only the bluetooth portion of code, and add some printfs after [this line](https://github.com/TioRuben/vedirect-antbms/blob/80db95011202ef14289c4f150fb2bc6b38f56248/main/bluetooth.c#L24)  `printf("%s",bmsData);` If it doesn't print anything, add some more printfs inside the `gapCallback` and `sppCallback` methods, inside of each `case` statement, and see if it tries to connect to BMS.

Finally, I see the your BMS is 17-24, mine is 7-16, so maybe the data packet changes. If you get action inside SPP callback, but don't get any `bmsData`, try to debug [this method](https://github.com/TioRuben/vedirect-antbms/blob/80db95011202ef14289c4f150fb2bc6b38f56248/components/antbms/antbms.c#L13) to see if the packet comes in different format.

Hope this helps with your project, regards

**Comment by livello** [comment]
@TioRuben Thank you very much for such a comprehensive answer!
I managed to connect to AntBMS and even get the status once. After that, the connection is terminated and a reboot is required to reconnect.

`W (5303) BT_APPL: new conn_srvc id:26, app_id:1

"C":15,"SOC":100,"BV":502,"BI":0,"P":0,"TM":26,"TB":27,"T1":26,"T2":25,"V1":3332,"V2":3333,"V3":3332,"V4":3332,"V5":3333,"V6":3559,"V7":3333,"V8":3332,"V9":3332,"V10":3332,"V11":3333,"V12":3333,"V13":3333,"V14":3334,"V15":3334,"V16":3328,"AT":15000000,"AR":14802734,"AC":2563169,"T3":25,"T4":25,"VMX":3559,"VMN":3332,"VMD":3347,"CHGS":1,"DCHS":1,"BALS":0

W (5933) BT_APPL: bta_jv_rfc_port_to_cb(port_handle:0x2):jv handle:0x0 not FOUND

W (5943) BT_RFCOMM: port_rfc_closed RFCOMM connection in server:0 state 3 closed: Closed (res: 19)
`

I forked your code and made some experiments 5d0ae4bc33a5dbd0b6d6d1bb48e3c2f0d31fe5d4

**Comment by livello** [comment]
https://github.com/TioRuben/vedirect-antbms/blob/80db95011202ef14289c4f150fb2bc6b38f56248/main/bluetooth.c#L58

I commented this line. Instant blackouts are gone. But I can not get the information from the bms again. Single reading only.

I experimented with resending the magic word. But it was not possible to receive a repeated response from the BMS.
e3049d2c42e001b5339b036f59cc99829650d3d9

**Comment by livello** [comment]
I've found 2 more magic words that works for my bms:
https://github.com/livello/vedirect-antbms/commit/faf725189c31ceae3162ae898e9036b5c03b2dd1

There is the project for raspberry pi. 
I've one. I'm going to check it:
https://github.com/JohnBerg60/bms-mqtt-broker/

**Comment by livello** [comment]
https://github.com/JohnBerg60/bms-mqtt-broker/ works like a charm with my antbms! Having raspi 4 or even a notebook for control charge and monitoring status is overkill.


![image](https://user-images.githubusercontent.com/15374538/154921923-6689ce5a-5e8d-4040-a9b9-8397e3c6bb92.png)
![image](https://user-images.githubusercontent.com/15374538/154922089-4e5ccc09-d8d6-475b-ba40-63b61c3427ad.png)
![image](https://user-images.githubusercontent.com/15374538/154922129-fb47c44c-6897-4dfa-8e72-412707356cc7.png)
![image](https://user-images.githubusercontent.com/15374538/154922209-d8a7245d-bfb9-485f-ab2a-ca0592d46df6.png)
